kubernetes:
  base:
    sourceRepo:
      name: blockscout
      org: cloudwalk
    monoRepo:
      url: git@github.com:cloudwalk/monorepo-gitops.git
      appsFolder: apps-config
      argoCDValues: helms/argocd/values.yaml
    containerRegistry:
      url: gcr.io/infinitepay-mainnet
    deployConfig:
      cluster: infinitepay-mainnet
      environment: production
      steps:
      - build
      - push
      - versioning
      - deploy
      service:
        asmRevision: asm-managed
  apps:
  - name: blockscout
    secretsManager:
      enabled: true
      provider: gcpsm
    imageRepoName: blockscout
    kind: deployment
    replicas: 3
    # hpa:
    #   antiAffinity:
    #     type: required
    #     conditions:
    #       - key: app
    #         value: blockscout
    #   maxReplicas: 5
    #   minReplicas: 1
    #   targetCPUUtilizationPercentage: 50
    envs:
    - name: ETHEREUM_JSONRPC_WS_URL
      value: wss://mainnet.cloudwalk.io/ws
    - name: ETHEREUM_JSONRPC_HTTP_URL
      value: https://rpc.mainnet.cloudwalk.io
    - name: ETHEREUM_JSONRPC_VARIANT
      value: geth
    - name: PORT
      value: "4000"
    - name: NETWORK
      value: "CloudWalk"
    - name: SUBNETWORK
      value: "Mainnet"
    - name: SUPPORTED_CHAINS
      value: '[ { "title": "CloudWalk Testnet", "url": "https://explorer.mainnet.cloudwalk.io/", "test_net?": true } ]'
    - name: POOL_SIZE
      value: '5'
    - name: POOL_SIZE_API
      value: '5'
    - name: COIN_NAME
      value: CWN
    - name: ENABLE_TXS_STATS
      value: true
    - name: SHOW_TXS_CHART
      value: true
    - name: CHAIN_ID
      value: '2009'
    - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
      value: true
    - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
      value: true
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 3Gi
    service:
      istio: false
      healthcheck:
        initialDelaySeconds: 240
        interval: 10
        path: /
        port: 4000
        timeoutSeconds: 15
      ports:
        - containerPort: 4000
          name: app
          virtualservice:
            gateway: default
            hosts:
              - blockscout.services.mainnet.cloudwalk.io
              - explorer.mainnet.cloudwalk.io
