kubernetes:
  base:
    sourceRepo:
      name: blockscout
      org: cloudwalk
    monoRepo:
      url: git@github.com:cloudwalk/monorepo-gitops.git
      appsFolder: apps-config
      argoCDValues: helms/argocd/values.yaml
    containerRegistry:
      url: gcr.io/infinitepay-mainnet
    deployConfig:
      cluster: infinitepay-mainnet
      environment: production
      steps:
      - build
      - push
      - versioning
      - deploy
      service:
        asmRevision: asm-managed
  apps:
  - name: blockscout
    secretsManager:
      enabled: true
      provider: gcpsm
    imageRepoName: blockscout
    kind: deployment
    replicas: 1
    envs:
    - name: ETHEREUM_JSONRPC_WS_URL
      value: ws://cloudwalk-network-bs.cloudwalk-network-production:9946
    - name: ETHEREUM_JSONRPC_HTTP_URL
      value: http://cloudwalk-network-bs.cloudwalk-network-production:9934
    - name: ETHEREUM_JSONRPC_VARIANT
      value: geth
    - name: PORT
      value: '4000'
    - name: NETWORK
      value: CloudWalk
    - name: SUBNETWORK
      value: Mainnet
    - name: SUPPORTED_CHAINS
      value: '[ { "title": "CloudWalk Mainnet", "url": "https://explorer.mainnet.cloudwalk.io/",
        "test_net?": false }, { "title": "CloudWalk Testnet", "url": "https://explorer.testnet.cloudwalk.io/",
        "test_net?": true } ]'
    - name: LOGO
      value: /images/cloudwalk_full.png
    - name: LOGO_FOOTER
      value: /images/cloudwalk_full.png
    - name: BLOCKSCOUT_VERSION
      value: 4.1.1-beta
    - name: RELEASE_LINK
      value: https://github.com/cloudwalk/blockscout/releases/tag/v4.1.1-beta
    - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
      value: 'true'
    - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
      value: 'true'
    - name: TRACE_LAST_BLOCK
      value: '0'
    - name: POOL_SIZE
      value: '15'
    - name: POOL_SIZE_API
      value: '15'
    resources:
      limits:
        cpu: 3000m
        memory: 4Gi
      requests:
        cpu: 3000m
        memory: 3Gi
    service:
      healthcheck:
        initialDelaySeconds: 30
        interval: 10
        path: /
        port: 4000
        timeoutSeconds: 15
      ports:
        - containerPort: 4000
          name: app
          virtualservice:
            gateway: default
            hosts:
              - blockscout.services.mainnet.cloudwalk.io
              - explorer.mainnet.cloudwalk.io
