kubernetes:
  base:
    sourceRepo:
      name: blockscout
      org: cloudwalk
    monoRepo:
      url: git@github.com:cloudwalk/monorepo-gitops.git
      appsFolder: apps-config
      argoCDValues: helms/argocd/values.yaml
    containerRegistry:
      url: gcr.io/infinitepay-testnet
    deployConfig:
      cluster: infinitepay-testnet
      environment: staging
      steps:
      - build
      - push
      - versioning
      - deploy
      service:
        asmRevision: asm-managed
      version: 03ea334de5bbcf39c2e08ce9f958f3a6420eb97d
  apps:
  - name: blockscoutapp
    secretsManager:
      enabled: true
      provider: gcpsm
    imageRepoName: blockscout
    kind: deployment
    replicas: 1
    envs:
    - name: ETHEREUM_JSONRPC_WS_URL
      value: ws://10.30.159.129:3000?app=blockscout
    - name: ETHEREUM_JSONRPC_HTTP_URL
      value: http://10.30.159.129:3000
    - name: ETHEREUM_JSONRPC_VARIANT
      value: geth
    - name: PORT
      value: '4000'
    - name: NETWORK
      value: CloudWalk
    - name: SUBNETWORK
      value: Testnet
    - name: SUPPORTED_CHAINS
      value: '[ { "title": "CloudWalk Mainnet", "url": "https://explorer.mainnet.cloudwalk.io/",
        "test_net?": false }, { "title": "CloudWalk Testnet", "url": "https://explorer.testnet.cloudwalk.io/",
        "test_net?": true } ]'
    - name: LOGO
      value: /images/cloudwalk_full.png
    - name: LOGO_FOOTER
      value: /images/cloudwalk_full.png
    - name: POOL_SIZE
      value: '50'
    - name: POOL_SIZE_API
      value: '50'
    - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
      value: 'true'
    - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
      value: 'true'
    - name: INDEXER_DISABLE_BLOCK_REWARD_FETCHER
      value: 'true'
    - name: BLOCKSCOUT_VERSION
      value: 4.1.1-beta
    - name: RELEASE_LINK
      value: https://github.com/cloudwalk/blockscout/releases/tag/v4.1.1-beta
    - name: INDEXER_MEMORY_LIMIT
      value: '4Gb'
    - name: DISABLE_EXCHANGE_RATES
      value: 'true'
    resources:
      limits:
        cpu: 3000m
        memory: 5Gi
      requests:
        cpu: 3000m
        memory: 5Gi
    service:
      istio: false
      healthcheck:
        initialDelaySeconds: 60
        interval: 10
        path: /
        port: 4000
        timeoutSeconds: 15
      ports:
      - containerPort: 4000
        name: app2
        virtualservice:
          gateway: internal
          hosts:
          - explorer.testnet.cloudwalk.io
          - explorer.testnet.cloudwalk.network
  - name: blockscoutledger
    secretsManager:
      enabled: true
      provider: gcpsm
    imageRepoName: blockscout
    kind: deployment
    replicas: 1
    envs:
    - name: ETHEREUM_JSONRPC_WS_URL
      value: ws://10.30.159.167:3000?app=blockscout
    - name: ETHEREUM_JSONRPC_HTTP_URL
      value: http://10.30.159.167:3000
    - name: ETHEREUM_JSONRPC_VARIANT
      value: geth
    - name: PORT
      value: '4000'
    - name: NETWORK
      value: CloudWalk
    - name: SUBNETWORK
      value: Testnet
    - name: SUPPORTED_CHAINS
      value: '[ { "title": "CloudWalk Mainnet", "url": "https://explorer.mainnet.cloudwalk.io/",
        "test_net?": false }, { "title": "CloudWalk Testnet", "url": "https://explorer.testnet.cloudwalk.io/",
        "test_net?": true } ]'
    - name: LOGO
      value: /images/cloudwalk_full.png
    - name: LOGO_FOOTER
      value: /images/cloudwalk_full.png
    - name: POOL_SIZE
      value: '50'
    - name: POOL_SIZE_API
      value: '50'
    - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
      value: 'true'
    - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
      value: 'true'
    - name: INDEXER_DISABLE_BLOCK_REWARD_FETCHER
      value: 'true'
    - name: BLOCKSCOUT_VERSION
      value: 4.1.1-beta
    - name: RELEASE_LINK
      value: https://github.com/cloudwalk/blockscout/releases/tag/v4.1.1-beta
    - name: INDEXER_MEMORY_LIMIT
      value: '4Gb'
    resources:
      limits:
        cpu: 3000m
        memory: 5Gi
      requests:
        cpu: 3000m
        memory: 5Gi
    service:
      istio: false
      healthcheck:
        initialDelaySeconds: 60
        interval: 10
        path: /
        port: 4000
        timeoutSeconds: 15
      ports:
      - containerPort: 4000
        name: app3
        virtualservice:
          gateway: internal
          hosts:
          - explorer-ledger.testnet.cloudwalk.io
          - explorer-ledger.testnet.cloudwalk.network